name: Selenium Script Run

# Run the workflow on push or schedule
on:
  push:
    branches:
      - main  # Or the branch you want to use
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    # Set up environment for Selenium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt for your dependencies (like selenium, dotenv, etc.)

      # If you are using Chrome and ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
        
      - name: Load environment variables
        run: |
          echo "ORCID_EMAIL=${{ secrets.ORCID_EMAIL }}" >> .env
          echo "ORCID_PASSWORD=${{ secrets.ORCID_PASSWORD }}" >> .env

      # Run the Selenium script
      - name: Run Selenium script
        env:
          ORCID_EMAIL: ${{ secrets.ORCID_EMAIL }}  # Store your ORCID credentials in GitHub Secrets
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
        run: |
          python src/refresh.py 
